In [ ]:
! pip install conda

ERROR: Ignored the following yanked versions: 3.0.6, 3.5.0, 3.7.0, 3.17.0, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.7, 4.0.8, 4.0.9, 4.1.2, 4.1.6, 4.2.6, 4.2.7, 4.3.13, 4.3.16
ERROR: Could not find a version that satisfies the requirement conda (from versions: none)
ERROR: No matching distribution found for conda


In [4]:
! git clone https://github.com/ur10/depth_anything_Expt.git

Cloning into 'depth_anything_Expt'...
remote: Enumerating objects: 268, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 268 (delta 0), reused 0 (delta 0), pack-reused 265 (from 2)
Receiving objects: 100% (268/268), 237.86 MiB | 16.24 MiB/s, done.
Resolving deltas: 100% (28/28), done.


In [5]:
import os
os.chdir('depth_anything_Expt')
!pip install -r requirements.txt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 89.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 305.1/305.1 kB 27.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.5/101.5 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 108.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.8/94.8 kB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.9/129.9 kB 13.3 MB/s eta 0:00:00
  Attempting uninstall: websockets
    Found existing installation: websockets 14.1
    Uninstalling websockets-14.1:
      Successfully uninstalled websockets-14.1
  Attempting uninstall: pillow
    Found existing installation: pillow 11.0.0
    Uninstalling pillow-11.0.0:
      Successfully uninstalled pillow-11.0.0
  Attempting uninstall: markupsafe
    Found 

In [1]:
! wget https://huggingface.co/spaces/LiheYoung/Depth-Anything/tree/main/checkpoints_metric_depth

--2025-01-07 12:26:58--  https://huggingface.co/spaces/LiheYoung/Depth-Anything/tree/main/checkpoints_metric_depth
Resolving huggingface.co (huggingface.co)... 13.249.213.119, 13.249.213.17, 13.249.213.95, ...
Connecting to huggingface.co (huggingface.co)|13.249.213.119|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 71147 (69K) [text/html]
Saving to: ‘checkpoints_metric_depth’

checkpoints_metric_ 100%[===================>]  69.48K   313KB/s    in 0.2s    

2025-01-07 12:26:59 (313 KB/s) - ‘checkpoints_metric_depth’ saved [71147/71147]



In [2]:
import os
!pwd
os.chdir('depth_anything_Expt/metric_depth')

/content


In [3]:
! mkdir checkpoints

In [4]:
!wget https://huggingface.co/spaces/LiheYoung/Depth-Anything/resolve/main/checkpoints/depth_anything_vitl14.pth
!wget https://huggingface.co/spaces/LiheYoung/Depth-Anything/resolve/main/checkpoints_metric_depth/depth_anything_metric_depth_indoor.pt

--2025-01-07 12:27:05--  https://huggingface.co/spaces/LiheYoung/Depth-Anything/resolve/main/checkpoints/depth_anything_vitl14.pth
Resolving huggingface.co (huggingface.co)... 13.249.213.119, 13.249.213.17, 13.249.213.95, ...
Connecting to huggingface.co (huggingface.co)|13.249.213.119|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs-us-1.hf.co/repos/b2/a8/b2a84b9a6ef705fba73e7ccec6a9728b3427d8b4c7f536eae186110f0cbd700f/6c6a383e33e51c5fdfbf31e7ebcda943973a9e6a1cbef1564afe58d7f2e8fe63?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27depth_anything_vitl14.pth%3B+filename%3D%22depth_anything_vitl14.pth%22%3B&Expires=1736510444&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTczNjUxMDQ0NH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zL2IyL2E4L2IyYTg0YjlhNmVmNzA1ZmJhNzNlN2NjZWM2YTk3MjhiMzQyN2Q4YjRjN2Y1MzZlYWUxODYxMTBmMGNiZDcwMGYvNmM2YTM4M2UzM2U1MWM1ZmRmYmYzMWU3ZWJjZGE5NDM5NzNhOW

In [5]:
!mv depth_anything_vitl14.pth checkpoints
!mv depth_anything_metric_depth_indoor.pt checkpoints

In [6]:
!mkdir data

In [ ]:
# !wget https://huggingface.co/spaces/LiheYoung/Depth-Anything/resolve/main/checkpoints_metric_depth/depth_anything_metric_depth_outdoor.pt
# !mv depth_anything_metric_depth_outdoor.pt checkpoints

--2024-12-19 00:16:05--  https://huggingface.co/spaces/LiheYoung/Depth-Anything/resolve/main/checkpoints_metric_depth/depth_anything_metric_depth_outdoor.pt
Resolving huggingface.co (huggingface.co)... 18.164.174.17, 18.164.174.23, 18.164.174.118, ...
Connecting to huggingface.co (huggingface.co)|18.164.174.17|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs-us-1.hf.co/repos/b2/a8/b2a84b9a6ef705fba73e7ccec6a9728b3427d8b4c7f536eae186110f0cbd700f/50a33976a4c909bd2284395d686bd644ce06c5c1c70f870d032b0eee93bdc56e?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27depth_anything_metric_depth_outdoor.pt%3B+filename%3D%22depth_anything_metric_depth_outdoor.pt%22%3B&Expires=1734826565&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTczNDgyNjU2NX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zL2IyL2E4L2IyYTg0YjlhNmVmNzA1ZmJhNzNlN2NjZWM2YTk3MjhiMzQyN2Q4YjRjN2Y1MzZlYWUxODYxMTBmMGNiZDcwMGY

In [7]:
# os.chdir('/content/Depth-Anything/metric_depth/data')
!mkdir -p data/SUNRGB-D/rgb
!mkdir -p data/SUNRGB-D/depth
!wget http://www.doc.ic.ac.uk/~ahanda/SUNRGBD-test_images.tgz
!wget https://www.doc.ic.ac.uk/~ahanda/sunrgb_test_depth.tgz
!tar -xvzf SUNRGBD-test_images.tgz -C data/SUNRGB-D/rgb
!tar -xvzf sunrgb_test_depth.tgz -C data/SUNRGB-D/depth

# !unzip SUNRGBD.zip
# !mkdir -p SUNRGB-D/rgb
os.chdir('/content/depth_anything_Expt/metric_depth')
# !rm -rf data
# !mkdir data

Streaming output truncated to the last 5000 lines.
sunrgbd_test_depth/3143.png
sunrgbd_test_depth/4089.png
sunrgbd_test_depth/4300.png
sunrgbd_test_depth/1279.png
sunrgbd_test_depth/4273.png
sunrgbd_test_depth/1785.png
sunrgbd_test_depth/436.png
sunrgbd_test_depth/3874.png
sunrgbd_test_depth/3986.png
sunrgbd_test_depth/1024.png
sunrgbd_test_depth/1564.png
sunrgbd_test_depth/1380.png
sunrgbd_test_depth/1031.png
sunrgbd_test_depth/4918.png
sunrgbd_test_depth/3221.png
sunrgbd_test_depth/4589.png
sunrgbd_test_depth/1796.png
sunrgbd_test_depth/243.png
sunrgbd_test_depth/772.png
sunrgbd_test_depth/721.png
sunrgbd_test_depth/5021.png
sunrgbd_test_depth/2190.png
sunrgbd_test_depth/2587.png
sunrgbd_test_depth/1243.png
sunrgbd_test_depth/3039.png
sunrgbd_test_depth/3045.png
sunrgbd_test_depth/4993.png
sunrgbd_test_depth/2183.png
sunrgbd_test_depth/2346.png
sunrgbd_test_depth/68.png
sunrgbd_test_depth/3462.png
sunrgbd_test_depth/3210.png
sunrgbd_test_depth/1063.png
sunrgbd_test_depth/466.png
sunr

In [8]:
import os
import shutil

def copy_jpg_files(source_folder, target_folder):
    # Ensure the target folder exists
    os.makedirs(target_folder, exist_ok=True)

    for root, dirs, files in os.walk(source_folder):
        for file in files:
            if file.lower().endswith('.png'):
                source_path = os.path.join(root, file)
                target_path = os.path.join(target_folder, file)

                # If a file with the same name exists, add a unique suffix
                counter = 1
                while os.path.exists(target_path):
                    name, ext = os.path.splitext(file)
                    target_path = os.path.join(target_folder, f"{name}_{counter}{ext}")
                    counter += 1

                shutil.copy2(source_path, target_path)
                print(f"Copied: {source_path} -> {target_path}")

# Example usage
source_folder = "/content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/sunrgbd_test_depth"  # Replace with the source folder path
target_folder = "/content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth"  # Replace with the target folder path

copy_jpg_files(source_folder, target_folder)

Streaming output truncated to the last 5000 lines.
Copied: /content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/sunrgbd_test_depth/2894.png -> /content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/2894.png
Copied: /content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/sunrgbd_test_depth/3688.png -> /content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/3688.png
Copied: /content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/sunrgbd_test_depth/3519.png -> /content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/3519.png
Copied: /content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/sunrgbd_test_depth/1409.png -> /content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/1409.png
Copied: /content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/sunrgbd_test_depth/3416.png -> /content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/3416.png
Copied: /content/depth_anything_Expt/metric_depth/data/SUNRGB-D/depth/sunrgbd_test_depth/

In [ ]:
# ! wget https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_09_26_drive_0001/2011_09_26_drive_0001_extract.zip
# ! unzip 2011_09_26_drive_0001_extract.zip
# ! wget https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_09_26_drive_0009/2011_09_26_drive_0009_extract.zip
# ! wget  https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data
# ! mv /content/Depth-Anything/metric_depth/raw_data_downloader.sh /content/Depth-Anything/metric_depth/data/Kitti/raw_data/2011_09_26
# ! chmod u+x raw_data_downloader.sh
# ! ./raw_data_downloader.sh
# ! mv ./raw_data_downloader.sh ../
# os.chdir('/content/Depth-Anything/metric_depth/data/Kitti/raw_data/')
# ! rm -rf 2011_09_26
# ! ./raw_data_downloader.sh

In [9]:
os.chdir('/content/depth_anything_Expt/metric_depth')

In [ ]:
# ! pwd
# # ! mkdir -p data/Kitti/raw_data/2011_09_26/2011_09_26_drive_0002_sync/image_02/data
# os.chdir('/content/Depth-Anything/metric_depth/')
# ! cp -r /content/Depth-Anything/metric_depth/2011_09_26/2011_09_26_drive_0001_extract/image_02  ./data/Kitti/raw_data/2011_09_26/2011_09_26_drive_0002_sync


In [ ]:
# ! pwd /content/Depth-Anything/metric_depth/data/Kitti/raw_data/2011_09_26/2011_09_26_drive_0009_sync/image_02/


/content/Depth-Anything/metric_depth


In [ ]:
# os.chdir('/content/Depth-Anything/metric_depth')

In [10]:
!pip install open3d

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 399.7/399.7 MB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 57.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.8/139.8 kB 14.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 16.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 9.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 53.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 48.1 MB/s eta 0:00:00
  Attempting uninstall: widgetsnbextension
    Found existing installation: widgetsnbextension 3.6.10
    Uninstalling widgetsnbextension-3.6.10:
      Successfully uninstalled widgetsnbextension-3.6.10
  Attempting uninstall: werkzeug
    Found existing installation: Werkzeug 3.1.3
    Uninstalling Werkzeug-3.1.3:
      Successfully uninstalled Werkzeug-3.1.3
  Attempting uninstall: Flask
    Found existing installation: Flask 3.1.0
    Unins

In [14]:
! mkdir -p /content/depth_anything_Expt/metric_depth/depth_map_new
! mkdir -p /content/depth_anything_Expt/metric_depth/point_cloud
! python evaluate.py -m zoedepth --pretrained_resource="local::./checkpoints/depth_anything_metric_depth_indoor.pt" -d sunrgbd

Streaming output truncated to the last 5000 lines.
  3% 171/5050 [02:28<1:09:41,  1.17it/s]tensor([[[[2.3564, 2.1547, 2.1313,  ..., 2.3516, 2.3671, 2.5462],
          [2.2104, 2.0488, 2.0469,  ..., 2.2577, 2.2553, 2.4040],
          [2.2202, 2.0630, 2.1117,  ..., 2.3255, 2.2772, 2.4299],
          ...,
          [1.1253, 1.0811, 1.1363,  ..., 0.6861, 0.6694, 0.6440],
          [1.1072, 1.0530, 1.0787,  ..., 0.6745, 0.6577, 0.6343],
          [1.5077, 1.2236, 1.1971,  ..., 0.6701, 0.6706, 0.7368]]]],
       device='cuda:0')
torch.Size([1, 1, 392, 518])
  3% 172/5050 [02:28<1:10:20,  1.16it/s]tensor([[[[1.8828, 1.6979, 1.6844,  ..., 1.5940, 1.6067, 1.7664],
          [1.6939, 1.6184, 1.6268,  ..., 1.5436, 1.5379, 1.5999],
          [1.7101, 1.6296, 1.7034,  ..., 1.6088, 1.5495, 1.6176],
          ...,
          [1.5351, 1.4440, 1.5322,  ..., 1.0652, 1.0182, 1.0374],
          [1.5155, 1.3968, 1.4496,  ..., 1.0152, 0.9926, 1.0154],
          [2.1034, 1.6963, 1.6535,  ..., 1.1113, 1.1177, 

In [19]:
import numpy as np
import open3d as o3d
import cv2 as cv
import os
FINAL_HEIGHT = 256
FINAL_WIDTH = 256

def depth_map_to_point_cloud(depth_map, image, intrinsics):
    """
    Convert a depth map and RGB image to a 3D point cloud with colors.

    Args:
        depth_map (np.ndarray): 2D array of depth values (H x W).
        image (np.ndarray): RGB image (H x W x 3).
        intrinsics (dict): Camera intrinsics with keys 'fx', 'fy', 'cx', 'cy'.

    Returns:
        o3d.geometry.PointCloud: Point cloud object.
    """
    # Validate dimensions
    print(depth_map.shape)
    print(image.shape[:2])
    if depth_map.shape != image.shape[:2]:
        raise ValueError("The dimensions of depth_map and image do not match!")

    # Intrinsics
    fx = intrinsics['fx']
    fy = intrinsics['fy']
    cx = intrinsics['cx']
    cy = intrinsics['cy']

    # Image dimensions
    height, width = depth_map.shape

    # Generate grid of (u, v) coordinates
    u, v = np.meshgrid(np.arange(width), np.arange(height))
    # Optional: Flip v-axis if necessary
    v = height - v - 1  # Uncomment if needed

    # Compute X, Y, Z coordinates
    Z = depth_map
    X = ((u - 256)/2) * Z / fx
    Y = ((v - 256)/2) * Z / fy

    # Stack into point cloud (H*W x 3)
    points = np.stack((X, Y, Z), axis=-1).reshape(-1, 3)
    print(f"The points we get are {points}")
    # Normalize and reshape image colors
    colors = (image / 255.0).reshape(-1, 3)  # Ensure range [0, 1]
    # colors.transpose(1,0,2)
    colors = colors[:, ::-1]
    # Create Open3D PointCloud object
    point_cloud = o3d.geometry.PointCloud()
    point_cloud.points = o3d.utility.Vector3dVector(points)
    point_cloud.colors = o3d.utility.Vector3dVector(colors)

    return point_cloud

def visualize_point_cloud(point_cloud):
    """Visualize a point cloud using Open3D."""
    o3d.visualization.draw_geometries([point_cloud])

# image = cv.imread(f'/home/ur10/Downloads/depth_map/image_6.png')
# depth_map = cv.imread(f'/home/ur10/Downloads/depth_map/depth_6.png')  # Example depth map
# print(depth_map.shape)
# depth_map = cv.cvtColor(depth_map, cv.COLOR_BGR2GRAY)
# depth_map = cv.resize(depth_map, (FINAL_HEIGHT, FINAL_WIDTH))
# print(depth_map)
# image = cv.resize(image, (FINAL_HEIGHT, FINAL_WIDTH))
# intrinsics = {'fx': 574.3343, 'fy': 574.3343, 'cx': 320., 'cy': 240}  # Example intrinsics


# image = image[:, ::-1]
# rgb_o3d = o3d.geometry.Image(image)
# depth_o3d = o3d.geometry.Image((depth_map).astype(np.uint16))  # Convert to mm if required
# rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
# rgb_o3d,
# depth_o3d,
# convert_rgb_to_intensity=False  # Keep RGB intact
# )
# intrinsics = o3d.camera.PinholeCameraIntrinsic(
# width=256, height=256, fx=574.3343, fy=574.3343, cx=319.5, cy=239.5
# )
# pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
# rgbd_image, intrinsics
# )

# # Flip the point cloud to match the Open3D coordinate system
# pcd.transform([[1, 0, 0, 0],
#                [0, -1, 0, 0],
#                [0, 0, -1, 0],
#                [0, 0, 0, 1]])
# o3d.visualization.draw_geometries([pcd])


# point_cloud = depth_map_to_point_cloud(depth_map,image, intrinsics)
# visualize_point_cloud(point_cloud)

depth_maps = os.listdir("/content/depth_anything_Expt/metric_depth/depth_map_new")
# extern_maps = os.l
for i in range(20):
    # Example usage
    image = cv.imread(f'/content/depth_anything_Expt/metric_depth/depth_map_new/image_{i}.png')
    depth_map = np.load(f'/content/depth_anything_Expt/metric_depth/depth_map_new/depth_{i}.npy')  # Example depth map
    extern_depth_image = cv.imread(f'/content/depth_anything_Expt/metric_depth/depth_map_new/pred_depth_{i}.png')
    print(depth_map.shape)
    # extern_depth_image = cv.cvtColor(extern_depth_image, cv.COLOR_BGR2GRAY)
    depth_map = cv.resize(depth_map, (FINAL_HEIGHT, FINAL_WIDTH))
    # depth_map = depth_map
    max_depth = np.max(depth_map)
    min_depth = np.min(depth_map)

    # depth_map = (max_depth - depth_map) + min_depth
    # depth_map = depth_map.astype(int)
    print(depth_map)
    print('Depth image - \n')
    # print(extern_depth_image)
    image = cv.resize(image, (FINAL_HEIGHT, FINAL_WIDTH))


    # image = np.ascontiguousarray(image)
    # image = image[:, ::-1]
    rgb_o3d = o3d.geometry.Image(image)
    depth_o3d = o3d.geometry.Image((depth_map).astype(np.float32))  # Convert to mm if required
    rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
    rgb_o3d,
    depth_o3d,
    convert_rgb_to_intensity=False  # Keep RGB intact
    )
    intrinsics = o3d.camera.PinholeCameraIntrinsic(
    width=256, height=256, fx=574.3343, fy=574.3343, cx=319.5, cy=239.5
    )
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
    rgbd_image, intrinsics
    )

    # Flip the point cloud to match the Open3D coordinate system
    pcd.transform([[0.5, 0, 0, 0],
                   [0, -0.5, 0, 0],
                   [0, 0, -1, 0],
                   [0, 0, 0, 1]])
    save_path = f'/content/depth_anything_Expt/metric_depth/point_cloud/point_cloud_{i}.ply'
    # o3d.visualization.draw_geometries([pcd]) #For Visualization
    o3d.io.write_point_cloud(save_path, pcd)

    # intrinsics = {'fx': 574.3343, 'fy': 574.3343, 'cx': 320., 'cy': 240}  # Example intrinsics
    # point_cloud = depth_map_to_point_cloud(depth_map,image, intrinsics)
    # visualize_point_cloud(point_cloud)
    # print("Point Cloud:\n", point_cloud)


# import os
# import cv2 as cv
# import numpy as np

# image_path = "/home/ur10/Downloads/depth_map1"
# images = os.listdir(image_path)


# for i in range(len(images)//2):
#     img = cv.imread(f"{image_path}/image_{i}.png")
#     img = cv.resize(img, (196, 238))
#     written = cv.imwrite(f'/home/ur10/Downloads/depth_map3/image_{i}.png',img)

#     if written:
#         print(f"Image {i+1} written ")

#     img = cv.imread(f"{image_path}/depth_{i}.png")
#     img = cv.resize(img, (192, 256))
#     img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
#     written = cv.imwrite(f'/home/ur10/Downloads/depth_map3/depth_{i}.png',img)
#     if written:
#         print(f"Depth {i+1} written ")

(392, 518)
[[2.5867574  2.5191326  2.5841787  ... 1.1325533  1.108331   1.1273433 ]
 [2.5370402  2.5159125  2.5836291  ... 1.1603041  1.1270491  1.0938903 ]
 [2.5859797  2.585104   2.6531882  ... 1.2084621  1.1709228  1.11663   ]
 ...
 [1.1695385  1.2383431  1.2783699  ... 1.0265518  0.9940953  0.9382034 ]
 [1.1409566  1.1952411  1.2380226  ... 0.9921923  0.9577491  0.91392434]
 [1.3544908  1.2194936  1.2418004  ... 0.9827867  0.96544904 1.0643138 ]]
Depth image - 

(392, 518)
[[1.0273368 1.0104458 1.0300682 ... 1.0550029 1.0384457 1.0527996]
 [0.9950615 1.0300894 1.0562472 ... 1.0723796 1.049129  1.0136832]
 [1.0125467 1.0611888 1.0932385 ... 1.1011515 1.0731269 1.0328546]
 ...
 [1.240098  1.3052189 1.3486825 ... 1.5564469 1.5020506 1.4309528]
 [1.2219582 1.2692599 1.3176825 ... 1.5148025 1.4550405 1.4005953]
 [1.4280286 1.3355663 1.36699   ... 1.575343  1.5319922 1.6527131]]
Depth image - 

(392, 518)
[[1.7393132 1.6590929 1.6952083 ... 2.3746014 2.3360026 2.4840581]
 [1.6690938 1.70

In [21]:
from google.colab import files


folder_path = "/content/depth_anything_Expt/metric_depth/point_cloud"

zip_path = "/content/depth_anything_Expt/metric_depth/point_cloud.zip"
shutil.make_archive(zip_path.replace(".zip", ""), 'zip', folder_path)

files.download(zip_path)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

##RUN the PromptDA version

In [5]:
import os
os.chdir('/content')
!git clone https://github.com/DepthAnything/PromptDA.git
os.chdir('PromptDA')
!pip install -r requirements.txt
!pip install -e .
# sudo apt install ffmpeg  # for video generation

fatal: destination path 'PromptDA' already exists and is not an empty directory.
Obtaining file:///content/PromptDA
  Preparing metadata (setup.py) ... done
  Running setup.py develop for promptda


In [6]:
!wget https://huggingface.co/depth-anything/promptda_vitl/resolve/main/model.ckpt

--2025-01-07 13:33:32--  https://huggingface.co/depth-anything/promptda_vitl/resolve/main/model.ckpt
Resolving huggingface.co (huggingface.co)... 13.35.202.40, 13.35.202.97, 13.35.202.121, ...
Connecting to huggingface.co (huggingface.co)|13.35.202.40|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs-us-1.hf.co/repos/06/9e/069e970793c44ca6e8b5f5551fdab7b2106668bf45f282d535a581fb80cc6e9f/4b3a3e0a60ea68e719cad3b2e22da8c95ce78f9559ee04824c064a2a06b0f10f?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model.ckpt%3B+filename%3D%22model.ckpt%22%3B&Expires=1736516012&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTczNjUxNjAxMn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zLzA2LzllLzA2OWU5NzA3OTNjNDRjYTZlOGI1ZjU1NTFmZGFiN2IyMTA2NjY4YmY0NWYyODJkNTM1YTU4MWZiODBjYzZlOWYvNGIzYTNlMGE2MGVhNjhlNzE5Y2FkM2IyZTIyZGE4Yzk1Y2U3OGY5NTU5ZWUwNDgyNGMwNjRhMmEwNmIwZjEwZj9yZXNwb25zZS1jb250ZW50LWRpc3B

In [7]:
pip install open3d

In [10]:
!cp -r /content/PromptDA/torchhub/ /content
import os
os.chdir('/content/PromptDA/')

In [11]:
from google.colab import output
output.enable_custom_widget_manager()
from promptda.promptda import PromptDA

In [12]:
from google.colab import output
output.enable_custom_widget_manager()

In [13]:
!gdown https://drive.google.com/uc?id=1kocVpoaV_mwhtNpu6QwWgwcyznbIibUV
# !wget https://drive.google.com/file/d/1kocVpoaV_mwhtNpu6QwWgwcyznbIibUV/view?usp=sharing
!mkdir -p /content/PromptDA/depth_map3
!mkdir -p /content/PromptDA/depth_results
!mkdir -p /content/PromptDA/point_cloud
!unzip /content/PromptDA/depth_map3.zip -d depth_map3

Downloading...
From: https://drive.google.com/uc?id=1kocVpoaV_mwhtNpu6QwWgwcyznbIibUV
To: /content/PromptDA/depth_map3.zip
100% 20.7M/20.7M [00:00<00:00, 39.1MB/s]
Archive:  /content/PromptDA/depth_map3.zip
replace depth_map3/depth_37.png? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: depth_map3/depth_37.png  
  inflating: depth_map3/depth_3.npy  
  inflating: depth_map3/image_48.png  
  inflating: depth_map3/depth_42.png  
  inflating: depth_map3/depth_81.png  
  inflating: depth_map3/depth_11.png  
  inflating: depth_map3/depth_57.npy  
  inflating: depth_map3/image_10.png  
  inflating: depth_map3/depth_9.png  
  inflating: depth_map3/image_37.png  
  inflating: depth_map3/image_31.png  
  inflating: depth_map3/depth_49.png  
  inflating: depth_map3/image_60.png  
  inflating: depth_map3/depth_65.png  
  inflating: depth_map3/image_12.png  
  inflating: depth_map3/depth_32.npy  
  inflating: depth_map3/depth_62.npy  
  inflating: depth_map3/image_42.png  
  inflating: depth_m

In [16]:
from promptda.promptda import PromptDA
from promptda.utils.io_wrapper import load_image, load_depth, save_depth
import numpy as np
import os
DEVICE = 'cuda'
images_path = '/content/PromptDA/depth_map3'
np_path = '/content/PromptDA/depth_results'
images = os.listdir(images_path)
model = PromptDA.from_pretrained("depth-anything/promptda_vitl").to(DEVICE).eval()
for i in range(50):
  image_path = f"{images_path}/image_{i}.png"
  prompt_depth_path = f"{images_path}/depth_{i}.png"
  image = load_image(image_path).to(DEVICE)
  prompt_depth = load_depth(prompt_depth_path).to(DEVICE) # 192x256, ARKit LiDAR depth in meters

  depth = model.predict(image, prompt_depth) # HxW, depth in meters
  print(depth)
  np.save(f'{np_path}/depth_{i}.npy', depth.squeeze().cpu().numpy())
  save_depth(depth, prompt_depth=prompt_depth, output_path=f'/content/PromptDA/depth_results/depth_{i}.png', image=image)

[INFO] Loading checkpoint from /root/.cache/huggingface/hub/models--depth-anything--promptda_vitl/snapshots/aa50906bc2afbd840ecf50709b2a36e5deeb32b4/model.ckpt
tensor([[[[0.1717, 0.1720, 0.1707,  ..., 0.1993, 0.2001, 0.1994],
          [0.1710, 0.1722, 0.1709,  ..., 0.1995, 0.2000, 0.1994],
          [0.1707, 0.1716, 0.1707,  ..., 0.1998, 0.2002, 0.1982],
          ...,
          [0.2215, 0.2213, 0.2216,  ..., 0.2390, 0.2390, 0.2386],
          [0.2204, 0.2209, 0.2214,  ..., 0.2390, 0.2390, 0.2389],
          [0.2189, 0.2230, 0.2215,  ..., 0.2390, 0.2387, 0.2389]]]],
       device='cuda:0')
tensor([[[[0.1829, 0.1859, 0.1864,  ..., 0.1520, 0.1484, 0.1282],
          [0.1821, 0.1862, 0.1863,  ..., 0.1503, 0.1475, 0.1282],
          [0.1828, 0.1845, 0.1838,  ..., 0.1531, 0.1485, 0.1270],
          ...,
          [0.2236, 0.2235, 0.2237,  ..., 0.2250, 0.2252, 0.2249],
          [0.2230, 0.2237, 0.2235,  ..., 0.2250, 0.2251, 0.2246],
          [0.2268, 0.2247, 0.2237,  ..., 0.2250, 0.2246, 

In [20]:
import numpy as np
import open3d as o3d
import cv2 as cv
import os
FINAL_HEIGHT = 256
FINAL_WIDTH = 256
def depth_map_to_point_cloud(depth_map, image, intrinsics):
    """
    Convert a depth map and RGB image to a 3D point cloud with colors.

    Args:
        depth_map (np.ndarray): 2D array of depth values (H x W).
        image (np.ndarray): RGB image (H x W x 3).
        intrinsics (dict): Camera intrinsics with keys 'fx', 'fy', 'cx', 'cy'.

    Returns:
        o3d.geometry.PointCloud: Point cloud object.
    """
    # Validate dimensions
    print(depth_map.shape)
    print(image.shape[:2])
    if depth_map.shape != image.shape[:2]:
        raise ValueError("The dimensions of depth_map and image do not match!")

    # Intrinsics
    fx = intrinsics['fx']
    fy = intrinsics['fy']
    cx = intrinsics['cx']
    cy = intrinsics['cy']

    # Image dimensions
    height, width = depth_map.shape

    # Generate grid of (u, v) coordinates
    u, v = np.meshgrid(np.arange(width), np.arange(height))
    # Optional: Flip v-axis if necessary
    v = height - v - 1  # Uncomment if needed

    # Compute X, Y, Z coordinates
    Z = depth_map
    X = ((u - 256)/2) * Z / fx
    Y = ((v - 256)/2) * Z / fy

    # Stack into point cloud (H*W x 3)
    points = np.stack((X, Y, Z), axis=-1).reshape(-1, 3)
    print(f"The points we get are {points}")
    # Normalize and reshape image colors
    colors = (image / 255.0).reshape(-1, 3)  # Ensure range [0, 1]
    # colors.transpose(1,0,2)
    colors = colors[:, ::-1]
    # Create Open3D PointCloud object
    point_cloud = o3d.geometry.PointCloud()
    point_cloud.points = o3d.utility.Vector3dVector(points)
    point_cloud.colors = o3d.utility.Vector3dVector(colors)

    return point_cloud

def visualize_point_cloud(point_cloud):
    """Visualize a point cloud using Open3D."""
    o3d.visualization.draw_geometries([point_cloud])

# image = cv.imread(f'/home/ur10/Downloads/depth_map/image_6.png')
# depth_map = cv.imread(f'/home/ur10/Downloads/depth_map/depth_6.png')  # Example depth map
# print(depth_map.shape)
# depth_map = cv.cvtColor(depth_map, cv.COLOR_BGR2GRAY)
# depth_map = cv.resize(depth_map, (FINAL_HEIGHT, FINAL_WIDTH))
# print(depth_map)
# image = cv.resize(image, (FINAL_HEIGHT, FINAL_WIDTH))
# intrinsics = {'fx': 574.3343, 'fy': 574.3343, 'cx': 320., 'cy': 240}  # Example intrinsics


# image = image[:, ::-1]
# rgb_o3d = o3d.geometry.Image(image)
# depth_o3d = o3d.geometry.Image((depth_map).astype(np.uint16))  # Convert to mm if required
# rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
# rgb_o3d,
# depth_o3d,
# convert_rgb_to_intensity=False  # Keep RGB intact
# )
# intrinsics = o3d.camera.PinholeCameraIntrinsic(
# width=256, height=256, fx=574.3343, fy=574.3343, cx=319.5, cy=239.5
# )
# pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
# rgbd_image, intrinsics
# )

# # Flip the point cloud to match the Open3D coordinate system
# pcd.transform([[1, 0, 0, 0],
#                [0, -1, 0, 0],
#                [0, 0, -1, 0],
#                [0, 0, 0, 1]])
# o3d.visualization.draw_geometries([pcd])


# point_cloud = depth_map_to_point_cloud(depth_map,image, intrinsics)
# visualize_point_cloud(point_cloud)

depth_maps = os.listdir("/content/PromptDA/depth_map3")
# extern_maps = os.l
for i in range(50):
    # Example usage
    image = cv.imread(f'/content/PromptDA/depth_map3/image_{i}.png')
    depth_map = np.load(f'/content/PromptDA/depth_results/depth_{i}.npy')  # Example depth map
    # extern_depth_image = cv.imread(f'/home/ur10/Downloads/depth_results/depth_{i}_depth.jpg')
    print(depth_map.shape)
    # extern_depth_image = cv.cvtColor(extern_depth_image, cv.COLOR_BGR2GRAY)
    depth_map = cv.resize(depth_map, (FINAL_HEIGHT, FINAL_WIDTH))
    # depth_map = depth_map
    max_depth = np.max(depth_map)
    min_depth = np.min(depth_map)

    depth_map = (max_depth - depth_map) + min_depth
    # depth_map = depth_map.astype(int)
    print(depth_map)
    print('Depth image - \n')
    # print(extern_depth_image)
    image = cv.resize(image, (FINAL_HEIGHT, FINAL_WIDTH))



    # image = image[:, ::-1]
    rgb_o3d = o3d.geometry.Image(image)
    depth_o3d = o3d.geometry.Image((depth_map).astype(np.float32))  # Convert to mm if required
    rgbd_image = o3d.geometry.RGBDImage.create_from_color_and_depth(
    rgb_o3d,
    depth_o3d,
    convert_rgb_to_intensity=False  # Keep RGB intact
    )
    intrinsics = o3d.camera.PinholeCameraIntrinsic(
    width=256, height=256, fx=574.3343, fy=574.3343, cx=319.5, cy=239.5
    )
    pcd = o3d.geometry.PointCloud.create_from_rgbd_image(
    rgbd_image, intrinsics
    )

    # Flip the point cloud to match the Open3D coordinate system
    pcd.transform([[0.5, 0, 0, 0],
                   [0, -0.5, 0, 0],
                   [0, 0, -1, 0],
                   [0, 0, 0, 1]])
    # o3d.visualization.draw_geometries([pcd]) # Visualization
    save_path = f'/content/PromptDA/point_cloud/point_cloud_{i}.ply'

    o3d.io.write_point_cloud(save_path, pcd)


    # intrinsics = {'fx': 574.3343, 'fy': 574.3343, 'cx': 320., 'cy': 240}  # Example intrinsics
    # point_cloud = depth_map_to_point_cloud(depth_map,image, intrinsics)
    # visualize_point_cloud(point_cloud)
    # print("Point Cloud:\n", point_cloud)


# import os
# import cv2 as cv
# import numpy as np

# image_path = "/home/ur10/Downloads/depth_map1"
# images = os.listdir(image_path)


# for i in range(len(images)//2):
#     img = cv.imread(f"{image_path}/image_{i}.png")
#     img = cv.resize(img, (196, 238))
#     written = cv.imwrite(f'/home/ur10/Downloads/depth_map3/image_{i}.png',img)

#     if written:
#         print(f"Image {i+1} written ")

#     img = cv.imread(f"{image_path}/depth_{i}.png")
#     img = cv.resize(img, (192, 256))
#     img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
#     written = cv.imwrite(f'/home/ur10/Downloads/depth_map3/depth_{i}.png',img)
#     if written:
#         print(f"Depth {i+1} written ")

(238, 196)
[[0.15075423 0.15060833 0.15106675 ... 0.12273921 0.12263519 0.12307782]
 [0.15144119 0.150733   0.1508828  ... 0.12268151 0.12266152 0.12308194]
 [0.15170495 0.15109314 0.15116778 ... 0.12251687 0.12296131 0.12411161]
 ...
 [0.10117301 0.10120867 0.10110232 ... 0.08351222 0.08363564 0.08384655]
 [0.10223918 0.10169081 0.1012598  ... 0.08353299 0.0835717  0.08360066]
 [0.10355635 0.10092111 0.10012256 ... 0.08365174 0.08368534 0.08358698]]
Depth image - 

(238, 196)
[[0.16321225 0.16124599 0.15996023 ... 0.19616543 0.2047583  0.21786945]
 [0.16392967 0.16131642 0.15984319 ... 0.19727291 0.20527603 0.21784323]
 [0.16342585 0.16202587 0.1614889  ... 0.19596909 0.2051456  0.21883963]
 ...
 [0.12255026 0.12252906 0.12248152 ... 0.12097226 0.12100466 0.12121031]
 [0.1226493  0.12239116 0.12236296 ... 0.12104142 0.12130913 0.12184083]
 [0.11928882 0.12062077 0.12177347 ... 0.12136282 0.12281559 0.12519372]]
Depth image - 

(238, 196)
[[0.21164836 0.21294826 0.21347839 ... 0.136130

Support for third party widgets will remain active for the duration of the session. To disable support:

In [ ]:
from google.colab import output
output.disable_custom_widget_manager()

Support for third party widgets will remain active for the duration of the session. To disable support:

In [ ]:
from google.colab import output
output.disable_custom_widget_manager()

In [21]:
from google.colab import files
import shutil

folder_path = "/content/PromptDA/point_cloud"

zip_path = "/content/PromptDA/point_clouds_prompt.zip"
shutil.make_archive(zip_path.replace(".zip", ""), 'zip', folder_path)

files.download(zip_path)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>